- name: Android Emulator Runner
  uses: ReactiveCircus/android-emulator-runner@v2.27.0

on:
  push:
    branches: [ "main" ]
    pull_request: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
