name: Instrumented tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:

      - name: Set up Java 11
        uses: actions/setup-java@v1
          with:
            java-version: 11

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: 21
          script: ./gradlew connectedCheck
